version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-devops-jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home  # Persistent Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Enable Jenkins to control Docker
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    restart: always

  snyk:
    image: snyk/snyk:docker
    container_name: my-devops-snyk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Enable Snyk to scan images
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
